banks:
  - admin.vybecard.com
  - app.n26.com
  - app.nickel.eu
  - app.qonto.com
  - clients.boursorama.com
  - clients.cmavignon.com
  - connexion-mabanque.bnpparibas
  - ebanking-ch3.ubs.com
  - epargnants.interepargne.natixis.fr
  - espace-client.hellobank.fr
  - espace-client.lanef.com
  - espaceclient.axa.fr
  - linxea-zen.avepargne.fr
  - m.ing.fr
  - mabanque.bnpparibas
  - mabanque.fortuneo.fr
  - mon.cmb.fr
  - monespace.lcl.fr
  - particuliers.societegenerale.fr
  - secure.bforbank.com
  - transatplan.banquetransatlantique.com
  - voscomptesenligne.labanquepostale.fr
  - www.altaprofits.com
  - www.aviva.fr
  - www.banque-rhone-alpes.fr
  - www.banquepopulaire.fr
  - www.bred.fr
  - www.caisse-epargne.fr
  - www.cic.fr
  - www.credit-agricole.fr
  - www.credit-cooperatif.coop
  - www.creditmutuel.fr
  - www.hsbc.fr
  - www.ibps.sud.banquepopulaire.fr
  - www.icgauth.banquebcp.fr
  - www.labanquepostale.fr
  - www.mgen.fr
  - www.monabanq.com
  - www.previ-direct.com
insurances:
  - adherent.gie-afer.fr
  - authentification.groupama.fr
  - connect.axa.fr
  - connect.maif.fr
  - connect.sogarep.fr
  - epargnant.amundi-ee.com
  - espace-assure.gmf.fr
  - espace-client.allianz.fr
  - espace-client.mma.fr
  - espace-personnel.direct-assurance.fr
  - espaceperso.mutuelledesmotards.fr
  - harmonie-et-moi.fr
  - myswisslife.fr
  - www.acommeassure.com
  - www.assu2000.fr
  - www.assurances-collectives.cm-cic.com
  - www.aviva.fr
  - www.creditmutuel-epargnesalariale.fr
  - www.lolivier.fr
  - www.maaf.fr
  - www.mgen.fr
  - www.monabanq.com
  - www.monespace.generali.fr
  - www.mutavie.fr
  - www.sylvea.fr

